#!/bin/bash


#echo "branch-id.txt" >> .gitignore
COMMIT_FILE=$1
echo -e " $COMMIT_FILE"
COMMIT_MSG=$(cat $1)




branch_name=$(git symbolic-ref --short HEAD |cut -d'/' -f 2) # Extracting proper branch name  for Branching Model
branch_type=$(git symbolic-ref --short HEAD |cut -d'/' -f 1)
project_id=$(echo "$branch_name" |cut -d '-' -f1) # Extracting project-id will print project-id Eg ATM
issueNumber=$(echo "$branch_name" |cut -d '-' -f2) #Extracting Issue Number. will print issue number Eg 5
IssueId=$project_id-$issueNumber; #Combine both to get IssueId Eg ATM-5
#COMMIT_MSG=$1;
PATTERN="PE|PLAT|ATO|PE|MNW|LOCKMARK|SSPORTAL|ADS";
#echo $PATTERN > pattern.txt 

# to compare this if valid patter present or not
echo $COMMIT_MSG > commit.txt;

# to check if patter present in branch name or not
echo $IssueId > branch-id.txt;

#checking if pattern is present in branch name or not
OutputIssue=$(findstr -L "PE PLAT ATM MNW LOCKMARK SSPORTAL ADS" branch-id.txt);


#checking if pattern is present in commit msg or not
OutputMessage=$(findstr -L "PE PLAT ATM MNW LOCKMARK SSPORTAL ADS" commit.txt);



echo "Pattern present in commit mesage: $OutputMessage";

echo "Pattern present in Issue ID: $OutputIssue";


#echo "Branch Name Passes : $1 \n";
echo "commit Message passed : $COMMIT_MSG \n";
echo "Branch Name: $branch_name \n";
echo "Branch Type: $branch_type \n";
echo "Project ID : $project_id \n";
echo "JIRA Ticket ID: $IssueId \n ";
Flag=0;

#checking if commit message has PATTERN or NOT
if [ ! -z "$OutputMessage" ] ; then
   echo "Valid : commit message has pattern"
   Flag=1;
   # Now check if Valid Issue ID present or not 
   if [ ! -z "$OutputIssue" ] ; then
   	echo "Valid: Valid Issues ID present in Branch name"; 
   	echo "Now compare if Issues ID matches in Commit Message";
   	#OutputCompare=$(egrep  -w  $IssueId  commit.txt);
	
	OutputCompare=$(findstr $IssueId commit.txt);
	
	echo $OutputCompare;
   	if [ ! -z  "$OutputCompare" ] ; then
   		echo "Valid: Commit Message has valid JIRA Ticket ID";
		Flag=1;   

	
		
	else
		echo "Invalid: Commit Message Does not have Valid JIRA Ticket ID";
		Flag=2;
	fi
   fi
else 
   echo "Invalid: No commit message has no PAttern"
   Flag=0;
fi


echo "flag value $Flag";

if [ 2  -eq  "$Flag" ] ; then
   echo "showing 2";

   exit 1;
elif [ "1" -eq "$Flag" ] ; then
	echo "showning 1";


else
   echo "showing 0";

exit 1;
fi


